// teacher/1212/2508-master-react-day5 (1)/day5/2-路由2-src/pages/home/Home.tsx
import React from 'react'
import {
  Outlet,
  Link,
  NavLink
} from 'react-router-dom'

const Home = () => {
  return (
    <div className="home">
      <main>
        <Outlet />
      </main>
      <footer>
        <NavLink to="/">电影</NavLink>
        <NavLink to="/cinema">影院</NavLink>
        <NavLink to="/mine">我的</NavLink>
      </footer>
    </div>
  )
}

export default Home

// teacher/1120/2508-master-vue-vue-day8/vue/vue-day8/2-嵌套路由和路由传参src/pages/Home.vue
<script setup>
import { RouterView, RouterLink } from 'vue-router'
</script>

<template>
  <div class="home">
    <main>
      <RouterView />
    </main>
    <footer>
      <RouterLink to="/home/film">电影</RouterLink>
      <RouterLink to="/home/cinema">影院</RouterLink>
      <RouterLink to="/home/mine">我的</RouterLink>
    </footer>
  </div>
</template>

<style lang='scss' scoped>
.home {
  width: 100vw;
  height: 100vh;
  display: flex;
  flex-direction: column;
  main {
    flex: 1;
    overflow: hidden;
  }
  footer {
    height: 50px;
    background: #fff;
    border-top: 1px solid #dddddd;
    display: flex;
    a {
      flex: 1;
      line-height: 50px;
      text-align: center;
    }
    .router-link-active {
      background: tomato;
    }
  }
}
</style>
