// teacher/1211/2508-master-react-day4-ts/react/day4-ts/2-受控组件-src/components/MyInput.tsx
import React, { useEffect, useState } from 'react'

interface Props {
  label: string
  defaultValue?: string
  value?: string
  onChange?: (value: string) => void
}

const MyInput: React.FC<Props> = ({
  label,
  value,
  defaultValue = '',
  onChange
}) => {
  const [inputText, setInputText] = useState(value ?? defaultValue)

  const change = (text: string) => {
    setInputText(text)
    onChange?.(text)
  }

  useEffect(() => {
    if (typeof value !== 'undefined' && value !== inputText) {
      setInputText(value)
    }
  }, [value])

  return (
    <div className="input_wrap">
      <span>{label}：</span>
      <input type="text" value={inputText} onChange={e => change(e.target.value)} />
      <i onClick={() => change('')}>清空</i>
    </div>
  )
}

export default MyInput

// teacher/1113/2508-master-vue-vue-day4/vue/vue-day4/2-组件v-model/components/MyInput.vue
<script>
export default {
  props: ['modelValue', 'label']
}
</script>

<template>
  <div class="row">
    <span>{{ label }}：</span>
    <input
      type="text"
      :value="modelValue"
      @input="e => $emit('update:modelValue', e.target.value)"
    >
  </div>
</template>

<style lang='scss' scoped>

</style>
