// teacher/1210/2508-master-react-day3/react/day3/2-自定义hook/components/Child2.jsx
import Child3 from './Child3'
import { useCount } from '../hooks/useCount'
import { useEffect } from 'react'

const Child2 = () => {
  const { num, start } = useCount(50)

  useEffect(() => {
    start()
  }, [])

  return (
    <div className="box">
      <h2>Child2 - {num}</h2>
      <Child3 />
    </div>
  )
}

export default Child2

// teacher/1119/2508-master-vue-vue-day7/vue/vue-day7/2-组合式函数/自定义hook/components/Child2.vue
<script setup>
import { onBeforeUnmount, ref } from 'vue'
import { format } from '../utils'
import { useCount } from '../hooks/useCount'

const { num } = useCount(80, true)


</script>

<template>
  <div class="child">
    <h3>child2</h3>
    <h4>{{ format(num * 1000) }}</h4>
    <ul>
      <li v-for="v in 5">{{ v }}</li>
    </ul>
  </div>
</template>

<style lang='scss' scoped>
.child {
  border: 3px solid red;
  padding: 20px;
}
</style>
