// myself/11.13/vue-eg/src/components/Child2.vue
<script>
import Child3 from './Child3.vue';

export default{
    props:['num'],
    components:{
        Child3
    },
    data(){
        return {
            
        }
    }
}
</script>

<template>
<div class="box">
    <h2>组件2</h2>
    <p>{{ num }}</p>
</div>
</template>

<style lang="scss" scoped>


</style>

// teacher/1210/2508-master-react-day3/react/day3/2-自定义hook/components/Child2.jsx
import Child3 from './Child3'
import { useCount } from '../hooks/useCount'
import { useEffect } from 'react'

const Child2 = () => {
  const { num, start } = useCount(50)

  useEffect(() => {
    start()
  }, [])

  return (
    <div className="box">
      <h2>Child2 - {num}</h2>
      <Child3 />
    </div>
  )
}

export default Child2
